version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: ./infra/DjangoDockerFile
    ports:
      - "8000:8000"
    volumes:
      - ./back:/usr/src/app
    depends_on:
      - postgres
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
